services:
  - type: web
    name: ai-wallet
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SOLANA_RPC_URL
        sync: false
      - key: NEXT_PUBLIC_TWITTER_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    nodeVersion: 18.17.0
    disk:
      name: npm-cache
      mountPath: /opt/render/project/src/.npm
      sizeGB: 1
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - next.config.js
        - public/**
        - src/** 